### ISSUE TITLE
BufferedRenderer is slower when zoomed.

### ISSUE THREAD

**Issue by AarnoT** [bitcraft/pyscroll#22]
I noticed quest.py spends a lot of time in pygame.transform.scale. When I removed the zoom from BufferedRenderer I went from ~70 fps to ~90 fps. Maybe it would be possible to save the zoomed surface rather than scale it every loop. You should be able to notice the issue if you run `python -m cProfile -s time quest.py` from the command prompt. The specific line is [here](https://github.com/bitcraft/pyscroll/blob/db7a81c9d7c2fadab6a46fd0637f2a1eb5678276/pyscroll/orthographic.py#L161).

**Comment by bitcraft** [comment]
Yes, I'm aware of that.  Unfortunately, saving a copy of the zoomed buffer would complicate rendering with sprites and tiles that cover them.  I'm not really interested in making a solution right now because it would complicate rendering and sprite placement.  90fps seems slow.  On my system, I get well over 400 fps at 1200x1600, that's with a 2x zoom.  Maybe there is another issue?

**Comment by AarnoT** [comment]
The 90 fps was on a cheap laptop. I just tried on my main computer and got 300 fps at 1680x1050 with zoom on. If it's difficult to fix then you don't need to bother with it. Thanks for the quick reply.
