### ISSUE TITLE
pygame2 rendered support

### ISSUE THREAD

**Issue by mcpalmer1980** [bitcraft/pyscroll#32]
Just wondering if bitcraft or anyone else is still interesting in pyscroll and if it might be ported to pygame2. I've already gotten pytmx to load images into textured images for the renderer, but porting pyscroll looks a bit harder. I don't want to try that until the final  pygame2 renderer API is documented.

**Comment by danielleravenwing** [comment]
It looks like it works in pygame2... except for some transparency issues.

**Comment by mcpalmer1980** [comment]
It works with software blitting in the developmental builds of pygame2, and I believe the transparency issues will be fixed in the official release. The software blitter is meant to be backwards compatible. The hardware accelerated sprite batching provided by pygame2.video is a different matter.

PyScroll would need a major overhaul to work with it I think. I'm not sure that buffered rendering would make since once hardware accelerated sprites are available, so long as pygame2 implements some sort of global transform.

**Comment by bitcraft** [comment]
@mcpalmer1980 pytmx/pyscroll works with pygame 2 without any changes needed.  i just found the transparency issue, but im not sure if that is due to my libs or pygame2.  its currently software sprites only at this point and i don't have plans for hardware sprites at the moment.  since pygame 2 is still a beta im just waiting to see where the community takes it.  there are some parts of pyscroll that would translate well for a hardware API, but you are correct, it would mostly be a rewrite to make the most of it.
