### ISSUE TITLE
Group draw method is inefficient

### ISSUE THREAD

**Issue by danielleravenwing** [bitcraft/pyscroll#33]
You could drastically improve the draw method if you only drew the sprites that are on screen.
Even manually removing the sprites that are off screen from the pyscroll group then adding them back in if they are on screen each clock cycle results in a 20FPS improvement in my game. But if such a function were built in it would run way better and it really wouln't be that hard to add.

**Comment by bitcraft** [comment]
Thats a good point.  I have not added a bounds check for game sprites because I assume that it is being done before sending sprites and camera info to pyscroll, since the sprites are expected to be transformed to screen space.  When developing, I was filtering out sprites which are on on the screen and the additional check would have been redundant.  I think a good compromise would be "bounds checking by default", with an option to turn it off.  Patches are appreciated :D

**Comment by bitcraft** [comment]
I realize now that you are specifically talking about the PyscrollGroup and I agree that it should have bounds checking by default.  The lower-level code which I was referring to earlier doesn't need it though.

**Comment by danielleravenwing** [comment]
Yeah, I was talking about the pyscollgroup :)

Implementing bounds checking in my game made it go from under 30fps to
about 60. So, it definitely improves performance a lot. I can't remember if
I attached to code that shows I patched it....

**Comment by bitcraft** [comment]
Added a check to the group which ignores sprites that are not on-screen.  Thanks again!
