### ISSUE TITLE
Converting a tile to an in-game sprite?

### ISSUE THREAD

**Issue by joereynolds** [bitcraft/pyscroll#38]
Hi,

I'm implementing pyscroll into my game and I'm having an issue with pyscroll immediately rendering out the entire map (which I expect). My question is, how do I convert this image into something usable for my game?

I have some sprite classes that I want to assign each tile to, I could do this with `LayeredUpdates` quite easily, literally just a call to `add` and then `draw` and it would work. Previously, I used pygame's `LayeredUpdates` and just called `draw` on the group and it would render everything out. But, if I do that with the `PyscrollGroup`, it renders those sprites on *top* of the map that pyscroll has also rendered.

Ideally what I'd do is just loop through all the tiles that have been made via pytmx/pyscroll (I'm using both), create the correct objects for them and then add those to the `PyscrollGroup` to be rendered out.

Happy to clarify a bit more, not sure I was too coherent :smile: 

Here's a gif to demonstrate what I mean, notice how the 'bombs' stay there (and the rocks too)? That's because of the map layer (I think). I need to convert the tiles in the map layer to the ones I have defined in my game, I've looked at some examples but couldn't find anything that addresses this.

![](https://i.imgur.com/l5TO9rW.gif)

For the record here's what it looked like before trying I started trying to implement pyscroll

![](https://i.imgur.com/RbejZ1W.gif)

Thanks for the help!

edit: I'm also open to hiding what pyscroll renders out and just having the camera follow the player, whatever works really

**Comment by bitcraft** [comment]
The pyscroll group is like the layered updates group.  If you are using
normal pygame sprites then you can set their layer and they will be
rendered correctly.  The layer you need to set depends on the tile layers
of your map.  So try adjusting the layer of the sprites and try again.

I don’t completely understand your problem though.  If you have sprites
that don’t leave the map then that is because they are still in the group.
Remove them from the group and they will not be rendered again.

If you want to change the tiles, then change the tile data and call redraw
on the pyscroll bufferedrender object.  Don’t do this every frame though,
or you will get bad framerates.

If it is a bottle neck, look at the animation code in pyscroll to see how
to change tiles in a fast way.  Specifically look at the tile queue and the
flush method.

For game entities that you expect to move around or change, I suggest you
add those as objects in Tiled, then create a sprite for each object in the
game.  This is the same for the rocks and the walls.  Make them Tiled
objects, then create sprites for them in game.  When you push or destroy
them, you won’t see the old tiles under it.

Try the object approach before manipulating the tile data.  It will be much
less work.

Leif

**Comment by joereynolds** [comment]
> For game entities that you expect to move around or change, I suggest you
add those as objects in Tiled...

That's what I was doing previously I had a `TileFactory` that would create the relevant tiles. If I leave that approach in though, you see that the above happens

Here's the code I used to use (in the process of refactoring to accommodate pyscroll)

```
        factory = TileFactory()
        for i, layer in enumerate(self._map):
            for _tile in layer.tiles():
                x, y = _tile[0], _tile[1]
                pix_x, pix_y = _tile[2][1][0], _tile[2][1][1]
                surface = graphics.subsurf((pix_x, pix_y))

                current_tile = self._map.get_tile_properties(x, y, i)
                if current_tile:
                    obj = self._create_tile(x, y, surface, current_tile, factory)
                    self.sprites.add(obj, layer=i)
```

**Comment by bitcraft** [comment]
If you use pyscroll, there is no need to render each tile.  Pyscroll will render the entire map and all sprites and there isn’t a need to manage individual tiles.  Look at the demo in the pyscroll app.  It is built to support pytmx with very little effort. 

Don’t make a sprite for each tile.  Just make a sprite for things you will interact with.  Tiled has object groups.  Create a object group for walls and rocks.  When loading the map, create sprites only for the destructible walls and sprites.  Don’t place them as tiles in tiled, because pyscroll will render the map exactly as it is shown in the editor.  

You can work around it by changing the layer data directly but I don’t recommend it.

By creating objects for every tile in the game, you lose the benefits of pyscroll, which are map animations, fast rendering, layers, and a camera that zooms and follows sprites.  

Consider sharing your code if you still can’t figure it out, but I suspect your issue is that your code isn’t using pyscroll the way it is supposed to be used.

**Comment by bitcraft** [comment]
You could *maybe* reuse your code by placing tiles on a layer, but set that layer visibility to false before saving it.  Pyscroll *shouldn’t* render it but I haven’t tried that for a long time.

**Comment by bitcraft** [comment]
Another thought.  As you make your objects, again, only for your rocks and barriers, set the layer data to 0 to prevent it from being rendered again. 

I believe it would be something like layer.data[y][x] = 0.  Or none.  I forget.  Notice y and x appear to be swapped.

**Comment by joereynolds** [comment]
Thanks bitcraft, I'll look into object groups, I'm probably just (ab)using Tiled and your libraries wrong. Thanks for your patience!

**Comment by joereynolds** [comment]
That seems to have done the trick, thanks for the help, I owe you!
