### ISSUE TITLE
Scaling algorithm?

### ISSUE THREAD

**Issue by joereynolds** [bitcraft/pyscroll#40]
Hi again,

I see that you use pygame.transform.scale (usually) as the function for scaling sprites in/out. What is the process you use to determine how much to scale in by depending on screen size? The reason I ask is because I have some other scenes (main menus, credits etc...) that are not in the `PyscrollGroup` and therefore aren't using the same scaling. I'd like it to be consistent so I'd like to replicate how you are doing it where possible.

My game is orthographic :)

Thanks!

**Comment by bitcraft** [comment]
the built in zoom/scaling uses `pygame.transform.scale`, though it is configurable.  https://github.com/bitcraft/pyscroll/blob/master/pyscroll/orthographic.py#L30
the way zooming/scale works is by changing the size of the internal buffer.  the buffer is what makes pyscroll work, so only changes of the map are drawn.  if the buffer is shrunk, then it is smaller than the screen, and must be scaled to match the screen size.  this causes the apparent size of the map and objects to increase "zoom".
your game object rects, images, etc are never changed.  idk if you want to exactly match your game to how pyscroll works because zoom is kinda a hack/clever trick that works based on how the pyscroll renderer works.

**Comment by joereynolds** [comment]
Okay fair enough, in the end I went for a simple solution of scaling based on the screen size

```
width_ratio = 16
height_ratio = 9
    
tile_width = screen_size[0]
tile_height = screen_size[1]
```

Thanks anyway!
