### ISSUE TITLE
AttributeError: 'BufferedRenderer' object has no attribute 'rect'.

### ISSUE THREAD

**Issue by FireFall-YT** [bitcraft/pyscroll#51]
what i should do with it?
![image](https://user-images.githubusercontent.com/58619409/140601682-0cda8c27-c2a1-48e7-9f9b-edf056069ae8.png)

**Comment by bitcraft** [comment]
You should not be trying to get the rect of the BufferedRenderer.  It is a private attribute and has a special use and ait s not supposed to be used by anything else.   If you want to position the Player object, they you can 1) get the position from the tmx map (using pixel coordinates) or 2) put the player object anywere, then center the group or 3) do nothing, because the camera will center on the player during `draw()`
if you just want to put the player in the center of the map, do the same thing as `quest.py`
```python
        # put the hero in the center of the map
        self.hero.position = self.map_layer.map_rect.center
```
https://github.com/bitcraft/pyscroll/blob/master/apps/tutorial/quest.py#L133
