### ISSUE TITLE
How to connect/render multiple maps dynamically 

### ISSUE THREAD

**Issue by qwetro** [bitcraft/pyscroll#7]
I'd like to build a game with a endless scroll map, I've built several map sections with TileMapEditor, but I dont know how to connect these sections while the game is running. when a section is at an end, I wanna randomly pickup a new section and join in without pause. can pyscroll do it?

**Comment by ri0t** [comment]
I'd be interested in that, too. Specifically in conjunction with autogenerated maps.

**Comment by bitcraft** [comment]
Hello, ri0t.  Pyscroll can handle arbitrarily large maps, perhaps limited by just memory for data storage.  If you want to you it for autogenerated maps, you can create a "map data" adapter class for pyscroll.  Just modify this class so that it can access your data, and pyscroll will render it.

https://github.com/bitcraft/pyscroll/blob/master/pyscroll/data.py


# Make data source for the map
map_data = YourGeneratedMapClass()

# Make the scrolling layer
screen_size = (400, 400)
map_layer = pyscroll.BufferedRenderer(map_data, screen_size)

# make the PyGame SpriteGroup with a scrolling map
group = pyscroll.PyscrollGroup(map_layer=map_layer)

If you have further questions, please open a new issue.  For a variety of reasons, I'm not interested in adding the ability to layout several map sections.

**Comment by Connor124** [comment]
I to would like to see the ability to switch maps upon request(entering buildings and such) an example of this was made by the people at Open Game Art: http://lpc.opengameart.org/static/lpc-style-guide/demo.html

**Comment by bitcraft** [comment]
If you want to change maps, then just create a new renderer and add your sprites.  @Connor124

**Comment by Connor124** [comment]
I think ill just stick with what ive got.

And btw how would i go about animating sprites?

**Comment by Connor124** [comment]
@bitcraft

**Comment by bitcraft** [comment]
@Connor124, please see issue #16

**Comment by Connor124** [comment]
I worked out changing maps also. Just take the code from the init function (in the demo) and remove the stuff you don't want, then run when the player is at certain coordinates.

**Comment by bitcraft** [comment]
decided to do some work on this.  there will be basic support to add dynamically add map sections with an offset.

**Comment by bitcraft** [comment]
demo of it working, but there are a few limitations.  see the code for info https://github.com/bitcraft/pyscroll/blob/v2.29/apps/demo/demo-stitched.py

**Comment by bitcraft** [comment]
this is now a supported feature
```python
        world_data = MapAggregator((16, 16))
        for filename, offset in [
            ("stitched0.tmx", (-20, -20)),
            ("stitched1.tmx", (0, -20)),
            ("stitched2.tmx", (20, -20)),
            ("stitched3.tmx", (-20, 0)),
            ("stitched4.tmx", (0, 0)),
            ("stitched5.tmx", (20, 0)),
            ("stitched6.tmx", (-20, 20)),
            ("stitched7.tmx", (0, 20)),
            ("stitched8.tmx", (20, 20)),
        ]:
            tmx_data = load_pygame(RESOURCES_DIR / filename)
            pyscroll_data = TiledMapData(tmx_data)
            world_data.add_map(pyscroll_data, offset)

        self.map_layer = pyscroll.BufferedRenderer(
            data=world_data,
            size=screen.get_size(),
            clamp_camera=True,
        )
```
