### ISSUE TITLE
Can't get lighting going correctly

### ISSUE THREAD

**Issue by ri0t** [bitcraft/pyscroll#8]
My idea is:
1. Have an object group in the map with lights
2. Render the map to a surface
3. Fill a same-size surface with black, adjust transparency depending on daylight
4. Draw and blit the light objects (simple filled white circle pngs) on the the daylight-surface
5. Multiply-blit the resulting compound light surface onto the map rendering

But i can't get the rendering of only the light objects needed in step 4.
I tried adding another group but it always renders the other layers, too, which obviously gives bad results. 
So, i'm looking for a way to render a group with only one specific (lights) object layer to a seperate surface. Is that possible? Or is there a better way to get proper lighting into the game?

**Comment by bitcraft** [comment]
What you are describing is possible, Ive done something like it before, see
the links below.  I played with a lot of combinations, and my technique was
pretty much what you are describing.  I would first create a layer of just
the lights first, render them to a surface, and use the resulting surface
at runtime...instead of 'rendering' the lights each frame....its slow!

There isn't a built in way for pyscroll to accomplish this.  You would
probably 1st render the lights surface, then blit portions over it in a way
so that it overlaps the pycroll group camera.  You can access the TMX data
from the data from PyScrollGroup._map_layer.data.tmx, then follow the pytmx
API to get your lights layer objects.  Hope that helps!  Something like the
following should work, in spirit (i might make a mistake here):

    layer = PyScrollGroup._map_layer.data.tmx.get_layer_by_name('lights')
    for obj in layer:
        # use the following attributes to draw cicles:
        # obj.x, obj.y, obj.width, obj.height

http://pytmx.readthedocs.org/en/latest/pytmx.html#pytmx.pytmx.TiledMap

https://gyazo.com/ffc17345e8412d2eb5a710cc50e4adc3
https://gyazo.com/03e27665ef1440e05f94a9202122fcd3
http://gyazo.com/ccf7b5b06a982a188a7f0f9971d24475
http://gyazo.com/02e2056077b542679c9e14b971462a50
http://gyazo.com/d2d906979e4ec82cd096a287c994eb68
http://gyazo.com/4b62ad36295e474ab324663e80b9e101
http://gyazo.com/299e493c65f474466fbf42a9f7d503a6
https://gyazo.com/a364a53ae3b9f025e5781a5a7727af51

I created a Tiled object layer and drew ellipses for the lights.  The
objects were used to create the areas for lighting.  This technique is very
slow in pygame, but if all your surfaces are the same format, and match the
display, it can be workable at lowish framerates.

Btw, there isn't really a better way, unless you are using numpy and some
wizardry there (which I cannot help you with).

**Comment by ri0t** [comment]
Thanks for the input, but is there a way to find out the actual rendering coordinates of objects?
I think it might be worthwile to pursuit rendering only what is visible, since i don't think rendering all light objectsis is feasible, as I'm working with huge maps.
I also would love to get at those coordinates for rendering speech bubbles above npc actor and sign objects.

**Comment by ri0t** [comment]
Ah, i think i have it. By just looking at the delta of object to player position, i should be able to work out both problems :)

**Comment by bitcraft** [comment]
pyscroll will translate coordinates of all the sprites in the group.  So if you use sprites, you can, as you mentioned, just offset the coordinates of the player sprite.  Use layers to ensure your speech bubbles draw over players.  Good luck.

**Comment by ri0t** [comment]
That works totally nice. Thanks for the hints, i did it exactly that way ;)
Can render a few lights (15-20 on one screen seems okay) but have to be careful about smoothing - I'm rendering circles with hungry gradients
